// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hTUQGUlsjNEFHdhgLUbeTmoBntEzglk',
    appId: '1:245509663887:web:6871d52e607bbed68954fa',
    messagingSenderId: '245509663887',
    projectId: 'applistatarefa-a5c03',
    authDomain: 'applistatarefa-a5c03.firebaseapp.com',
    databaseURL: 'https://applistatarefa-a5c03-default-rtdb.firebaseio.com',
    storageBucket: 'applistatarefa-a5c03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSCmWlPt7Es7sxwvscGYyeOasSGLBXVo',
    appId: '1:245509663887:android:b356e855cb73e3da8954fa',
    messagingSenderId: '245509663887',
    projectId: 'applistatarefa-a5c03',
    databaseURL: 'https://applistatarefa-a5c03-default-rtdb.firebaseio.com',
    storageBucket: 'applistatarefa-a5c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhd6Xm6nPV5Ce_tJ4KMjtY9vuZR6z1sE',
    appId: '1:245509663887:ios:2700927692e051428954fa',
    messagingSenderId: '245509663887',
    projectId: 'applistatarefa-a5c03',
    databaseURL: 'https://applistatarefa-a5c03-default-rtdb.firebaseio.com',
    storageBucket: 'applistatarefa-a5c03.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhd6Xm6nPV5Ce_tJ4KMjtY9vuZR6z1sE',
    appId: '1:245509663887:ios:2700927692e051428954fa',
    messagingSenderId: '245509663887',
    projectId: 'applistatarefa-a5c03',
    databaseURL: 'https://applistatarefa-a5c03-default-rtdb.firebaseio.com',
    storageBucket: 'applistatarefa-a5c03.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3hTUQGUlsjNEFHdhgLUbeTmoBntEzglk',
    appId: '1:245509663887:web:5dca19cafb3b4d768954fa',
    messagingSenderId: '245509663887',
    projectId: 'applistatarefa-a5c03',
    authDomain: 'applistatarefa-a5c03.firebaseapp.com',
    databaseURL: 'https://applistatarefa-a5c03-default-rtdb.firebaseio.com',
    storageBucket: 'applistatarefa-a5c03.firebasestorage.app',
  );
}
